version: '3.9'
services:
  wordpress:
    image: wordpress:6.4.2
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: websiteszoo 
      WORDPRESS_DB_PASSWORD: LP6u~m;Hp90~bHjJ 
      WORDPRESS_DB_NAME: websiteszoo 
    volumes:
      - ./code:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: LP6u~m;Hp90~bHjJ  
      MYSQL_DATABASE: websiteszoo  
      MYSQL_USER: websiteszoo  
      MYSQL_PASSWORD: LP6u~m;Hp90~bHjJ  
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    links:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: websiteszoo  
      PMA_PASSWORD: LP6u~m;Hp90~bHjJ  
